language: python

python:
  - "3.5"
  - "3.8"

install:
  - pip install coveralls pyparsing
  - python setup.py install

script:
  # run tests
  - bash runtests.sh
  # self-check using installed scripts
  - pystrict3.py pystrict3.py pystrict3lib/*.py

after_success: coveralls
