name: Test
on: [push, pull_request]
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: [3.7, 3.8, '3.10', '3']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install coveralls numpy flake8 pytest coverage-lcov rst2html5
      - name: Install package
        run: python -m pip install .
      - name: Lint with flake8
        # stop the build if there are Python syntax errors or undefined names
        run: flake8 pystrict3.py pystrict3lib/*.py --show-source
      - name: Check documentation
        # stop the build if there are Python syntax errors or undefined names
        if: ${{ !((matrix.python-version == '3.7') || (matrix.python-version == '3.6')) }}
        run: rst2html5 README.rst > README.html
      - name: Run tests
        run: make test
      - name: Self-test
        run: pystrict3.py --allow-redefining --import-any pystrict3.py pystrict3lib/*.py
      - name: Self-test (gendocstr)
        run: gendocstr.py gendocstr.py
      - name: Convert coverage output to lcov for coveralls
        run: |
          coverage combine
          coverage-lcov
          # make paths relative
          sed -i s,$PWD/,,g lcov.info
      - name: prepare coveralls partial upload
        if: ${{ !((matrix.python-version == '2.7') || (matrix.python-version == '3.5')) }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: lcov.info
          flag-name: run-${{ matrix.python-version }}
          parallel: true
        

  finish:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
